### ISSUE TITLE
[NOT VERY IMPORTANT] Can't seem to build..... Idk

### ISSUE THREAD

**Issue by Rainbowkittypaw** [SapphireMordred/Sapphire#120]
Like the title mentions, this isn't important and you don't need to bother answering.

Now that that's outta the way, I've installed everything but can't seem to build the solution. 

I'm brand new to this, so I have no idea what I'm doing.

If this annoys you or is not worth answering due to it's complexity and/or the fact that I couldn't use the damn thing even if i built it plz feel free to close this issue. Ty for your time.

**Comment by takhlaq** [comment]
please join our discord for troubleshooting 

though this project is still very much in early stages and not intended for the average user or production use

**Comment by SapphireMordred** [comment]
Closed since this is not an issue per se. As Demo said, come see us on discord to get some pointers as for how to proceed.
