### ISSUE TITLE
HateList regression after 4.1

### ISSUE THREAD

**Issue by itsMaru** [SapphireMordred/Sapphire#134]
HateList seems to be broken after 4.1 hit. Probably a structural change? ID seems to match

To replicate just whack a mob. It won't show up on the aggro list (and mob name color will not change to red)

**Comment by GokuWeedLord** [comment]
it seems that hatelist is now sent in 2 packets, the only difference being that from `0x22` to `0x28`, the value is different

**Comment by SapphireMordred** [comment]
Needs reinvestigation when mobs are readded. Closed for now.
