### ISSUE TITLE
how to contact?

### ISSUE THREAD

**Issue by Icehunter** [SapphireMordred/Sapphire#136]
Hi @SapphireMordred is there a way for us to talk about something outside GitHub?

Discord:
Icehunter#5476

Thanks!

**Comment by itsMaru** [comment]
Hello!

https://discord.gg/KfrZCkx

**Comment by AcedArmy** [comment]
You could join the discord (https://discord.gg/KfrZCkx) and send him a pm

**Comment by Icehunter** [comment]
Thanks!
