### ISSUE TITLE
If level 30+ Game will set you back to 0 on login

### ISSUE THREAD

**Issue by AcedArmy** [SapphireMordred/Sapphire#178]
Seems to either be a problem with the GM lvl, GM exp command or to do with levels or db and needs to be looked into. Also After about 2 login attempts or zoning the game seems to crash and will keep crashing you on login

**Comment by itsMaru** [comment]
Please retest on latest master

**Comment by SapphireMordred** [comment]
Has anyone checked this recently?

**Comment by GokuWeedLord** [comment]
I haven't had this happen to me, used GM lv/exp commands on a few characters without issue

**Comment by AcedArmy** [comment]
I can not get this to trigger anymore myself. Going to close the issue
