### ISSUE TITLE
Investigate static analysis tools

### ISSUE THREAD

**Issue by ayyaruq** [SapphireMordred/Sapphire#192]
Just a checklist issue to keep track of what works, what doesn't, and what needs input from others or more experimenting. Goal is to get static analysis and code style checks into CI, ideally on hosted platform but seems most don't support C++ projects.

- [x] clang-check (LLVM)
- [x] clang-format (LLVM)
- [x] clang-tidy (LLVM)
- [x] cppcheck (Google)
- [x] infer (Facebook)
- [x] oclint

**Comment by ayyaruq** [comment]
oclint has some good output but it's hard to configure and is seriously slow. I think it's good for periodic local checks or validating large patch sets but I would definitely not want to automate it or bake it into CI.

**Comment by ayyaruq** [comment]
[clang-format](https://clang.llvm.org/docs/ClangFormat.html) tentative config added, please see #193 for config plus example output.

**Comment by ayyaruq** [comment]
[Clang Tidy](http://clang.llvm.org/extra/clang-tidy/) is neat but I think more useful again for manual checks locally. It's too inconsistent with how it works with `clang-check` and `clang-format` and tends to change things in ways that aren't how you configured it. Version is pegged to LLVM, but I don't think it's quite mature enough yet.

**Comment by ayyaruq** [comment]
[Infer](http://fbinfer.com) has nice output and basic HTML reports, and essentially covers the same info (plus a few thread safety and memory access issues) as other tools like cppcheck. The main thing is that it's *really* slow and multi step, absolutely not at all good for CI. The documentation says it's good for CI but having used it a bit I disagree. I linked some bug output gists in Discord as well.

**Comment by ayyaruq** [comment]
[Clang Check](https://clang.llvm.org/docs/ClangCheck.html) is the best tool I've tried so far. It essentially dumps compiler warnings and a few more detailed potential bug sources. I find it's not as detailed as cppcheck for raw output, but it catches a lot of stylistic and syntax things that cppcheck misses. The biggest downside is you can't configure exclusions, so libraries like mysqlconnector get all their override spam included.

[cppcheck](http://cppcheck.sourceforge.net) on the other hand is crazy verbose and gives a tonne of output. There's no configuration for it so it'd need to be handled with very explicit CLI flags. There are integrations for most editors and whatnot though. While it does include what rules are violated, it doesn't give you exact syntax points or how you can fix them like the Clang tools.

**Comment by ayyaruq** [comment]
After using all of the above tools, I think a tightly tuned cppcheck in CI is the best way to go. Clang tools (especially format and check) are amazing for git hooks but I think getting the output of them in a meaningful way on pull requests isn't easy until something like CodeClimate properly supports them. Being able to diff `clang-format` output against a PR would be really nice, but no services that I know of will manage and comment the PR with the info. The same goes for other Clang tools. The best way forward, that I can see for now, is just cppcheck in Travis. Open to any thoughts or feedback on this, plus questions etc.

**Comment by itsMaru** [comment]
Status on this + #193 ? Master has heavily changed since

**Comment by ayyaruq** [comment]
Sorry for the radio silence, I think it's ok to close this issue now. My last comment pretty much addresses it as is and after checking a quick git pull I don't think enough has meaningfully changed. If a 3rd party service properly supported C++ on GitHub hook it might be worth doing but other than cppcheck, I don't think there's enough benefit for the effort to get tools like this into the CI process. If I get some time I'll try to push a cppcheck config but right now my focus is more on CMake.
