### ISSUE TITLE
Sapphire Bugs (You know you love em ;)

### ISSUE THREAD

**Issue by AcedArmy** [SapphireMordred/Sapphire#20]
# NOTE: These Are General Things I have Noticed In My Time Playing On The Sapphire Server
Bugs that have been resolved will have a check mark in the box next to them!

## Levelup/Exp Bugs

- [x] Leveling Up Past Level 1 Causes The Red Cross To Be Displayed Next To EXP Bar

## Command Bugs

- [ ] GM Icon Command (Only Does Offline or Unstable Connection Status)

## Player/HUD Bugs
- [x] When Attuning Hud Disappears And Only Reappears When Canceling The Event Or Finishing Attuning
- [x] Player HP Does Not Regen Even After Death
- [x] MP Regens at 1 MP (Not Sure If Bug Or Not)
- [x] AFK Status Not Resetting After Put On User From Being AFK
## Quest/NPC Bugs

- [x] Archer Quests Seems Needs To Be Done (Does Not Continue Event And Just Loops)
- [ ] Mother Miounne After Accepting Close To Home Calls On A Script/Actor Unrelated

##  Mobs/Actions

- [x]  Causes Crash Sometimes After Killing About 5 Mobs When Getting EXP
- [ ] Striking Dummy's Are Under The Ground
- [ ] All Race Mobs (example. Lalafell) Use The Same Human Model With No Clothes
- [x] Actions Tend To Be Used 2 Times When Pressed Once (Noticed With Lancer True Thrust)
- [ ] On Mob Respawn Enemy's Have No HP 

# More Might Be Coming Soon...

**Comment by itsmaru** [comment]
could also add AFK status not resetting - thought of making an issue but it seemed small enough to be able to fit in here.

basically having the AFK status slapped on you and then being active once more doesn't return you to the previous status. we'll probably have to store the previous status somewhere.

**Comment by AcedArmy** [comment]
AFK Status bug added from request of @itsmaru to Player/Hud Bugs

**Comment by AcedArmy** [comment]
Fixed Close To Home (Archer) quest in #114

**Comment by GokuWeedLord** [comment]
was going to mention this previously but forgot

- mother miounne quest should be fixed now, I don't think I implemented the whole quest but at this point but you do zone into the correct area at least after accepting the quest and the cutscene plays
- there's an issue with the close to home quest cutscene in limsa not playing correctly when you talk to baderon not playing the cutscene at all and just zoning you into the real limsa
- GM icon isn't actually a bug, it's just that the other statuses aren't implemented so only implemented statuses will show https://github.com/SapphireMordred/Sapphire/blob/f017389ad14ff936276c2c4295d1c5de12130b80/src/servers/sapphire_zone/Actor/Player.cpp#L147-L186 although we need a better way of doing this for sure

**Comment by SapphireMordred** [comment]
looks like remaining things here need to be reinvestigated, closing this.
