### ISSUE TITLE
When merging script update branch  shapphirelibs doesn't pull correct tly

### ISSUE THREAD

**Issue by t999uk** [SapphireMordred/Sapphire#205]
![](https://i.imgur.com/F4xYVkL.jpg) when merging script branch it doesn't pull the latest shapphirelibs and you have to manually download the missing files

**Comment by takhlaq** [comment]
git pull origin --recurse-submodules
git submodule update --init
cd src/libraries && git checkout master && git pull origin master

where origin is whatever `git remote -v` shows as `https://github.com/SapphireMordred/Sapphire`

**Comment by t999uk** [comment]
Thanks that fixed it
