### ISSUE TITLE
Too many actors triggering client player despawning itself

### ISSUE THREAD

**Issue by itsMaru** [SapphireMordred/Sapphire#210]
Basically if there are too many actors, the client despawns itself, effectively locking the player out with no way back in without recreating the session.

This has likely to do with the internal actor table used for ranged actors.

![image](https://user-images.githubusercontent.com/30917768/34395582-8352dbf4-eb48-11e7-9571-b269e103fa1e.png)

**Comment by NotAdam** [comment]
this may actually be fixed now with the rewrite of actor spawnindex allocation (#259). What could have been happening before was the client would run out of spawn indexes and then default to index 0, which is where we spawn the local player causing it to get overwritten with another actor instead

Mordred was saying it could be related to how cells work too, but as bnpcs were stripped out I can't say for sure whether it's actually fixed at the moment as there's no easy way to test

**Comment by SapphireMordred** [comment]
Closing for now, (should be fixed)
