### ISSUE TITLE
4.3 stuff

### ISSUE THREAD

**Issue by Minoost** [SapphireMordred/Sapphire#296]
4.2 -> 4.3

(Unconfirmed)
15C -> 172
15D -> 173
15E -> 174
15F -> 175
160 -> 176
161 -> 177
162 -> 178 (ActorCast)

[goes on until 178 -> 18E]

**Comment by Minoost** [comment]
https://github.com/SapphireMordred/Sapphire/blob/cc1726184891910d335b77234800ea262a2190a6/src/servers/sapphire_lobby/GameConnection.cpp#L478-L479

is changed from 4000(sb) to 4300 (Patch 4.3)

**Comment by flawedmatrix** [comment]
Some more 4.3 opcodes:
https://github.com/ff14wed/xivnet/commit/a00ff7a946217949d93dd0a5d9ca516a811a39cb

**Comment by ff14wed** [comment]
Updated Action structs: https://github.com/ff14wed/xivnet/commit/61a28fa62de75b4ab7cc1db16b056a90ca8260b2
