### ISSUE TITLE
JSON Payload for Lobby issues

### ISSUE THREAD

**Issue by itsMaru** [SapphireMordred/Sapphire#328]
Currently, having two or more characters on a single account bring issues to the client.
This is caused by the recent patch's changes to the JSON structure for the lobby.

As for people looking for a workaround, you can create two accounts for now and make a character in each of them

Suggested by @AcedArmy - would be great if someone looked into getting all the details showing properly on the lobby as well.

**Comment by SapphireMordred** [comment]
I don't think this is related to the json payload but changes in the structure around it.
I have not verified though.

**Comment by SapphireMordred** [comment]
This may be a local issue on my end, i will investigate later.
