### ISSUE TITLE
New Character Items Missing

### ISSUE THREAD

**Issue by Bilibox** [SapphireMordred/Sapphire#356]
**Description:**

New characters should start with Weathered Ring, Choker, Wristlets, and earings

https://xivdb.com/item/15133/weathered+ring
https://xivdb.com/item/15132/weathered+wristlets
https://xivdb.com/item/15131/weathered+earrings
https://xivdb.com/item/15130/weathered+choker

**Current behaviour:**

Characters spawn with nothing on their right side of the character equip screen

**Expected behaviour:**

Character should start with Weathered items. 15133/2/1/0

**Comment by itsMaru** [comment]
Thanks for opening an issue, I'll be taking a look shortly

**Comment by takhlaq** [comment]
this should be fixed in https://github.com/SapphireMordred/Sapphire/pull/369

**Comment by Bilibox** [comment]
Issue fixed
