### ISSUE TITLE
Load GM rank per player 

### ISSUE THREAD

**Issue by SapphireMordred** [SapphireMordred/Sapphire#41]
Currently a players GM rank is hardcoded, this should instead be moved to a DB field and loaded accordingly.

**Comment by HoshyRyu** [comment]
Hello. I hope I am in the right place to ask. I apologize if not. I was wondering about GM level. I have server running and was wondering if I can make myself GM and how? Is it like with SLB server through DB or is it automatic when running. Thank you for your time and any feedback and help.
